# This is a team comp calculator for merge tactics for when you have the target dummy.

traits = {"clan",
          "brawler",
          "noble",
          "blaster",
          "electric",
          "wizard",
          "juggernaut",
          "ace",
          "avenger",
          "goblin",
          "ghost",
          "assassin",
          "archer",
          "fire"}

units = {"knight":(2, "noble", "juggernaut"),
         "spear goblin": (2, "goblin", "blaster"),
         "goblin": (2, "goblin", "assassin"),
         "skeleton dragon": (2, "ghost", "archer"),
         "barbarian": (2, "clan, brawler"),
         "wizard": (2, "fire, wizard"),
         "archer": (2, "clan", "archer"),
         "musketeer": (3, "noble", "blaster"),
         "valkyrie": (3, "clan", "juggernaut"),
         "pekka": (3, "ace", "avenger"),
         "prince": (3, "noble", "brawler"),
         "giant skeleton": (3, "ghost", "brawler"),
         "dart goblin": (3, "goblin", "archer"),
         "electro giant": (3, "electric", "avenger"),
         "executioner": (3, "ace", "blaster"),
         "baby dragon": (4, "fire", "blaster"),
         "witch": (4, "ghost", "avenger"),
         "electro wizard": (4, "electric", "wizard"),
         "mega knight": (4, "ace", "brawler"),
         "princess": (4, "noble", "archer"),
         "royal ghost": (4, "ghost", "assassin"),
         "bandit": (4, "ace", "assassin"),
         "goblin machine": (4, "goblin", "juggernaut"),
         "golden knight": (5, "noble", "assassin"),
         "skeleton king": (5, "ghost", "juggernaut"),
         "archer queen": (5, "clan", "avenger")} # units["name"] = cost, trait1, trait2
